### ISSUE TITLE
widen main content pane

### ISSUE THREAD

**Issue by rpmcfong** [countableSet/antora-ui#10]
We may consider widening the main content pane. Someone showed me [Flux](https://fluxcd.io/docs/get-started/) which fills a landscape screen. I'm not sure if there's a reason why the default Antora style leaves a gap on the right.

**Comment by countableSet** [comment]
I noticed that too and thought it was a little weird when I was using my laptop screen, but didn't notice it was much when using a monitor, I suppose my windows size is smaller on the monitor. Seems reasonable to improve it 👍🏻 I don't think there's a reason why Antora style leaves such a gap. 🤷🏻‍♀️ 

Looks like there's a issues open for it https://gitlab.com/antora/antora-ui-default/-/issues/157 open 1 year ago 😱

**Comment by countableSet** [comment]
Current toc width is around 216px on my 14in laptop screen.
<img width="390" alt="Screen Shot 2022-04-19 at 10 13 38 PM" src="https://user-images.githubusercontent.com/226476/164155242-c23e05e7-87eb-4d3a-94cb-dd141f6798cb.png">

which aligns with https://github.com/countableSet/antora-ui/blob/ac4c9c6b2aa53d891ab776879430feab0ef95f82/src/css/vars-dark.css#L146-L149

Flux width is percentage based, around 16.6666%
<img width="695" alt="Screen Shot 2022-04-19 at 10 09 21 PM" src="https://user-images.githubusercontent.com/226476/164155433-8ddb4116-bbe1-40bb-a2f5-47f44b40b266.png">

We can switch to a percentage as well, something around 235px instead look ok.
<img width="340" alt="Screen Shot 2022-04-19 at 10 16 36 PM" src="https://user-images.githubusercontent.com/226476/164155565-84f95e6c-f7cb-4d69-b9ae-a9eb941d3665.png">

| Before | After | 
| ------ | ------ |
|  <img width="1792" alt="Screen Shot 2022-04-19 at 10 19 12 PM" src="https://user-images.githubusercontent.com/226476/164155870-b8894605-ed2e-4aa1-8dd7-3ac53b1f7b1d.png"> | <img width="1792" alt="Screen Shot 2022-04-19 at 10 19 29 PM" src="https://user-images.githubusercontent.com/226476/164155906-7522403d-7886-4299-a753-e0c611f0741b.png"> |
