### ISSUE TITLE
style monospace more distinctly

### ISSUE THREAD

**Issue by rpmcfong** [countableSet/antora-ui#11]
Someone noted that the monospace text is hard to differentiate on a page. Comparing it to some other styles like the one for [k8s](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/), I suspect it's because:

* the font Antora uses is too similar to the variable width font
* the background is too close in contrast

**Comment by countableSet** [comment]
+1 for this the code blocks and inline blocks don't have enough contrast, at least in dark mode. Is the light mode contrast ok? I'm thinking yes? Maybe `Roboto Mono` isn't cutting it and we should switch to something else as well.

**Comment by countableSet** [comment]
ohh maybe I'll try out something like this
`font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu;`
That san fransisco font seem like the new thing to use https://developer.apple.com/fonts/ 🙃  than just roboto

![Screen Shot 2022-04-20 at 12 07 24](https://user-images.githubusercontent.com/226476/164304474-7e4252b0-04f9-4898-90a3-816772adf690.png)
k8s is using
`font-family: SFMono-Regular,Menlo,Monaco,Consolas,liberation mono,courier new,monospace;`

**Comment by rpmcfong** [comment]
Ty; will give this a try and see how people like it. Using the github approach sounds reasonable b/c it's so widely used. I need to check my notification settings too; I didn't even see any of these comments. :(
