### ISSUE TITLE
clipboard icon missing from source boxes

### ISSUE THREAD

**Issue by ryan-fong-wd** [countableSet/antora-ui#28]
we noticed an issue when we upgraded from [b2593412518](https://github.com/countableSet/antora-ui/releases/tag/b2593412518) on 2022-06-30 to [b4706517879](https://github.com/countableSet/antora-ui/releases/tag/b4706517879) on 2023-04-14. the clipboard icon that appears in the upper right of source text boxes was missing and said _copy icon_. this was most noticeable on pages that were not located at the root, such as https://dovah.workday.build/framework/maintainers/index.html

the url to the icon was incorrectly placed at the current directory *./img/octicons-16.svg#view-clippy*
![wrong url](https://github.com/user-attachments/assets/ac96dfeb-1255-4f7c-93f8-be4b1372a050)

strangely, this problem does not occur when i view the site from a local file system (windows 11 and firefox 128).

it should be a relative path back to the root and _ directory, such as *../../_/img/octicons-16.svg#view-clippy*
![correct url](https://github.com/user-attachments/assets/e4199b1f-5f0c-49c7-83c5-dbe1fd8636fd)

i haven't tried pinpointing the exact change that caused this but justin thinks it might have been this [commit](https://github.com/countableSet/antora-ui/commit/39af887045bf42ee48caeb4cbcda232553b1677a) that altered the *uiRootPath* variable.

**Comment by countableSet** [comment]
🤔 I can't seem to reproduce the issue. I tried the following (with these docs https://github.com/countableSet/semantic-version-plugin/tree/main/docs and added a non-root module to try too 👍)

- file system viewing in safari (which you also mentioned was ok) (e.g. file:///Users/rachel/code/countableset/semantic-version-plugin/build/site/research/gradle-plugin.html)
- using a http server to serve the files locally `python3 -m http.server` (e.g. http://localhost:8000/research/gradle-plugin.html)
- the final built version uploaded to cloudflare pages here https://semantic-version.gradle.poolside.dev/research/gradle-plugin

not sure what else to try yet to get it to reproduce

----

but I did find this error message in the browser console  🤦‍♀ 

```
Not allowed to load local resource: file:///Users/rachel/code/countableset/semantic-version-plugin/build/site/research/_/js/header.js
```

or (which I have all the csp stuff on, so that message isn't that helpful)

```
Refused to execute https://semantic-version.gradle.poolside.dev/research/_/js/header.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
```

will trying fixing that first to see if it helps 🤞

**Comment by countableSet** [comment]
mind trying out build [b10334410526](https://github.com/countableSet/antora-ui/releases/tag/b10334410526)?

**Comment by ryan-fong-wd** [comment]
hi and thank you for the quick reply! i will try the new version this week.

**Comment by ryan-fong-wd** [comment]
b10334410526 does not resolve the issue. i can try b4706437655 and prior releases this week to try and isolate the cause.

**Comment by countableSet** [comment]
> b10334410526 does not resolve the issue. i can try b4706437655 and prior releases this week to try and isolate the cause.

dang 🤦‍♀  mind checking a few things with `b10334410526`?
- does `header.js` in `<head></head>` is loading correctly?
- does it have the same behavior with `./img/octicons-...` incorrect src reference on the effected pages?

**Comment by countableSet** [comment]
ok I think I found an upstream improvement and also fixed a bug with the variable set. Try build [b10363827687](https://github.com/countableSet/antora-ui/releases/tag/b10363827687) 👍 

----

are you by chance changing the `partials/` file in the playbook config?

```
supplemental_files:
    - path: partials/footer-scripts.hbs
      contents: |
```

if you are try changing it to include all the extra junk too
```
<script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
```

I think it might be just
```
<script src="{{{uiRootPath}}}/js/site.js"></script>
```

**Comment by ryan-fong-wd** [comment]
> > b10334410526 does not resolve the issue. i can try b4706437655 and prior releases this week to try and isolate the cause.
> 
> dang 🤦‍♀ mind checking a few things with `b10334410526`?
> 
>     * does `header.js` in `<head></head>` is loading correctly?
> 
>     * does it have the same behavior with `./img/octicons-...` incorrect src reference on the effected pages?

the console doesn't report any warning on header.js (firefox 129.0). i only see two problems

* GET https://dovah.workday.build/favicon.ico [HTTP/2 404 0ms]
* downloadable font: Glyph bbox was incorrect (glyph ids 33 55 62 81 82 83 84 87 88 89 90 112 119 120 123 139 159 162 164 166 178 184 185 217 218 272 273 274 275 279 281 284 290 291 292 309 310 319 321 323 326 329 330 331 332 333 334 339 341 347 349 351 352 353 354 357 358 361 366 367 370 371 414 431 436 444 445 458 460 464 465 483 505 508 511 514 516 517 518 520 521 538 539 546 568 574 579 580 585 586 594 596 599 602 603 616 618 622 627 629 630 633 634 638 643 645 651 654 665 675 685 686 688 691) (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1) source: https://dovah.workday.build/_/font/fontawesome-webfont.woff2?v=4.7.0 

the favicon.ico placement might be a little bit off. i had tampered with that configuration in the antora.yml playbook at one point.

**Comment by ryan-fong-wd** [comment]
> ok I think I found an upstream improvement and also fixed a bug with the variable set. Try build [b10363827687](https://github.com/countableSet/antora-ui/releases/tag/b10363827687) 👍

oh, cool. i can try that one next.

> are you by chance changing the `partials/` file in the playbook config?

yes, it's minimal though.
* i have a `header-content.hbs` and a `footer-scripts.hbs`
```yaml
ui:
  bundle:
    url: /ui-bundle.zip
  supplemental_files: ./supplemental_ui
```

> if you are try changing it to include all the extra junk too

* `header-content.hbs` doesn't use the uiRootPath placeholder
* `footer-scripts.hbs` includes the placeholder where it's used

```js
<script src="{{{uiRootPath}}}/js/site.js"></script>
{{#if env.SITE_SEARCH_PROVIDER}}
{{> search-scripts}}
{{/if}}
<script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
```

**Comment by countableSet** [comment]
> <script src="{{{uiRootPath}}}/js/site.js"></script>
> {{#if env.SITE_SEARCH_PROVIDER}}
> {{> search-scripts}}
> {{/if}}
> <script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>

Ohh you are totally missing the id (`id="site-script"`)  and data (`data-ui-root-path="{{{uiRootPath}}}"`) fields in the foot-scripts for the site.js import.

try changing `<script src="{{{uiRootPath}}}/js/site.js"></script>` to `<script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>` 🤞

**Comment by ryan-fong-wd** [comment]
> Ohh you are totally missing the id (`id="site-script"`) and data (`data-ui-root-path="{{{uiRootPath}}}"`) fields in the foot-scripts for the site.js import.

oh, that fixed it. i didn't realize it was that fragile! i modified the footer to remove the "this is a fork" message a while ago but it didn't break the clipboard icon until we changed the ui-bundle.zip.

should i still commit the latest ui-bundle.zip?

**Comment by countableSet** [comment]
> > Ohh you are totally missing the id (`id="site-script"`) and data (`data-ui-root-path="{{{uiRootPath}}}"`) fields in the foot-scripts for the site.js import.
> 
> oh, that fixed it. i didn't realize it was that fragile! i modified the footer to remove the "this is a fork" message a while ago but it didn't break the clipboard icon until we changed the ui-bundle.zip.

yeah looks like those fields were added by the upstream, probably to make loading better 🤦‍♀ 
https://gitlab.com/antora/antora-ui-default/-/commit/02bd7175d71e9d9f0564411bd8d4091d43dd5fb5

> should i still commit the latest ui-bundle.zip?

yeah I would use the latest version since I also added another fix they added as well for the clipboard widget 👍 
https://gitlab.com/antora/antora-ui-default/-/commit/91de243e4cd1d84effe43af31c1e01e7231ba568

**Comment by ryan-fong-wd** [comment]
cool, it still works the latest ui-bundle. thank you so much! ❤️

**Comment by countableSet** [comment]
nice! thanks for opening an issue ❤
